[TASK] Rework Altera Nios II tools
- Combine drivers.sh and apps.sh to have a single code base for creating
  apps and drivers Nios II projects.
- Rename creation scripts and setting files.
- Generated stack library name is forwarded to app.sh via temporary
  file. This avoids searching for the library, what could lead to errors
  if other libraries are created in the same working directory.

Change-Id: I571366554b02e60516a9d90f6ec89af9be33f93a

diff --git a/drivers/altera-nios2/drv_daemon/build/create-this-app b/drivers/altera-nios2/drv_daemon/build/create-this-app
--- a/drivers/altera-nios2/drv_daemon/build/create-this-app
+++ b/drivers/altera-nios2/drv_daemon/build/create-this-app
@@ -1,6 +1,7 @@
+#!/bin/bash
 ################################################################################
 #
-# Drivers creation settings file for Altera Nios II
+# Create this app for Altera Nios II
 #
 # Copyright (c) 2014, Bernecker+Rainer Industrie-Elektronik Ges.m.b.H. (B&R)
 # All rights reserved.
@@ -28,19 +29,52 @@
 # SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ################################################################################
 
-DRV_NAME=drv_daemon
+# process arguments
+BOARD_PATH=
+ARGS=
+while [ $# -gt 0 ]
+do
+    case "$1" in
+        --debug)
+            ARGS+="$1 "
+            ;;
+        --board)
+            shift
+            BOARD_PATH=$1
+            ;;
+        --rebuild)
+            rm -f bsp*/Makefile lib*/Makefile Makefile
+            ;;
+        --help)
+            echo "$ create-this-app [OPTIONS]"
+            echo "OPTIONS:"
+            echo "  --debug         ... App is created for debug"
+            echo "  --rebuild       ... Forces rebuild"
+            echo "  --board [PATH]  ... Path to board design (board.settings)"
+            exit 1
+            ;;
+        *)
+            ;;
+    esac
+    shift
+done
 
-# Driver sources
-DRV_SOURCES="\
-${OPLK_BASE_DIR}/drivers/altera-nios2/drv_daemon/daemon.c \
-"
+if [ -z "${OPLK_BASE_DIR}" ]; then
+    # Find oplk root path
+    SCRIPTDIR=$(dirname $(readlink -f "${0}"))
+    OPLK_BASE_DIR=$(readlink -f "${SCRIPTDIR}/../../../..")
+fi
 
-DRV_INCLUDES="\
-${OPLK_BASE_DIR}/stack/include \
-${OPLK_BASE_DIR}/stack/include/kernel \
-"
+APP_PATH=${OPLK_BASE_DIR}/drivers/altera-nios2/drv_daemon/build
 
-CFG_DRV_ARGS="\
-"
+# include functions
+. ${OPLK_BASE_DIR}/tools/altera-nios2/shell_functions
 
-DRV_OPT_LEVEL=-O2
+if [ -z "${BOARD_PATH}" ]; then
+    # user selects from existing boards
+    BOARD_PATH=`select_dir_abs ${OPLK_BASE_DIR}/hardware/boards 'board.settings' 'grep -e dual -e drv'`
+    test $? -ne 0 && echo "$0 failed!" && exit
+fi
+
+chmod +x ${OPLK_BASE_DIR}/tools/altera-nios2/app.sh
+${OPLK_BASE_DIR}/tools/altera-nios2/app.sh ${APP_PATH} ${BOARD_PATH} ${ARGS}
